server:
  port: 8080
logging:
  level:
    ru.podgoretskaya: DEBUG
    org.springframework.security: TRACE
spring:
  datasource:
    driver_class_name:
      org.postgresql.Driver
    url:
      jdbc:postgresql://localhost:5432/Authorization
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jpa:
    hibernate:
      ddl-auto: 'update'

